### ISSUE TITLE
`cam` module not present in esp32 object

### ISSUE THREAD

**Issue by the-maldridge** [RealTimeLogic/Xedge32#15]
I am trying to follow along with [this post](https://realtimelogic.com/articles/Streaming-ESP32CAM-Images-to-Multiple-Browsers-via-MQTT) and have run into an issue trying to run the camtest.lsp example.

It appears that my build does not include the lua bindings for the camera module:

```
> for k, v in pairs(esp32) do print("key " .. k) ; end
key loglevel
key mac
key i2cmaster
key pwmchannel
key gpio
key sdcard
key execute
key apinfo
key wscan
key adc
key netconnect
key uart
key pwmtimer
``` 

Despite it being compiled and linked into the firmware:

```
[ 91%] Linking C static library libesp32-camera.a
[ 91%] Built target __idf_esp32-camera
```

I assume somewhere I needed to tell the build system that I fetched the esp32-camera component and I'd like the bindings made available, but I don't see where to do that.  Advice is appreciated.

**Comment by surfskidude** [comment]
Did you enable it using idf.py menuconfig ?

**Comment by jjsch-dev** [comment]
@the-maldridge you need to run **idf.py menuconfig**, navigate to xedge configuration and enable camera, before building the project, clone [esp32-camera ](https://github.com/espressif/esp32-camera) component.

![image](https://github.com/RealTimeLogic/Xedge32/assets/55675185/76998bef-a5a7-4cff-b191-83725d03d573)
